logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: test
    root_packages: com.apps.test
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
eclipselink:
   ddl:
       auto:
            create:
                   delete: false
jwt:
  secret: hithere1
